echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000
echo -n "HELO text\n" | nc localhost 8000